// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: services/companyInfoGetter/companyInfoGetter.proto

package companyInfoGetter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCompanyInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inn string `protobuf:"bytes,1,opt,name=inn,proto3" json:"inn,omitempty"`
}

func (x *GetCompanyInfoRequest) Reset() {
	*x = GetCompanyInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_companyInfoGetter_companyInfoGetter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCompanyInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyInfoRequest) ProtoMessage() {}

func (x *GetCompanyInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_companyInfoGetter_companyInfoGetter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyInfoRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyInfoRequest) Descriptor() ([]byte, []int) {
	return file_services_companyInfoGetter_companyInfoGetter_proto_rawDescGZIP(), []int{0}
}

func (x *GetCompanyInfoRequest) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

type GetCompanyInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inn   string `protobuf:"bytes,1,opt,name=inn,proto3" json:"inn,omitempty"`
	Kpp   string `protobuf:"bytes,2,opt,name=kpp,proto3" json:"kpp,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Chief string `protobuf:"bytes,4,opt,name=chief,proto3" json:"chief,omitempty"`
}

func (x *GetCompanyInfoResponse) Reset() {
	*x = GetCompanyInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_companyInfoGetter_companyInfoGetter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCompanyInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyInfoResponse) ProtoMessage() {}

func (x *GetCompanyInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_companyInfoGetter_companyInfoGetter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyInfoResponse.ProtoReflect.Descriptor instead.
func (*GetCompanyInfoResponse) Descriptor() ([]byte, []int) {
	return file_services_companyInfoGetter_companyInfoGetter_proto_rawDescGZIP(), []int{1}
}

func (x *GetCompanyInfoResponse) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

func (x *GetCompanyInfoResponse) GetKpp() string {
	if x != nil {
		return x.Kpp
	}
	return ""
}

func (x *GetCompanyInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCompanyInfoResponse) GetChief() string {
	if x != nil {
		return x.Chief
	}
	return ""
}

var File_services_companyInfoGetter_companyInfoGetter_proto protoreflect.FileDescriptor

var file_services_companyInfoGetter_companyInfoGetter_proto_rawDesc = []byte{
	0x0a, 0x32, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x74, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x6e, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x6e, 0x6e, 0x22,
	0x66, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6e, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x6e, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x70, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x70, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x69, 0x65, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x63, 0x68, 0x69, 0x65, 0x66, 0x32, 0x58, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x74, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6e, 0x69, 0x61, 0x6b, 0x72, 0x31, 0x73, 0x2f, 0x73, 0x68, 0x74, 0x72, 0x61, 0x66, 0x6f, 0x76,
	0x6e, 0x65, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x74, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_companyInfoGetter_companyInfoGetter_proto_rawDescOnce sync.Once
	file_services_companyInfoGetter_companyInfoGetter_proto_rawDescData = file_services_companyInfoGetter_companyInfoGetter_proto_rawDesc
)

func file_services_companyInfoGetter_companyInfoGetter_proto_rawDescGZIP() []byte {
	file_services_companyInfoGetter_companyInfoGetter_proto_rawDescOnce.Do(func() {
		file_services_companyInfoGetter_companyInfoGetter_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_companyInfoGetter_companyInfoGetter_proto_rawDescData)
	})
	return file_services_companyInfoGetter_companyInfoGetter_proto_rawDescData
}

var file_services_companyInfoGetter_companyInfoGetter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_companyInfoGetter_companyInfoGetter_proto_goTypes = []interface{}{
	(*GetCompanyInfoRequest)(nil),  // 0: GetCompanyInfoRequest
	(*GetCompanyInfoResponse)(nil), // 1: GetCompanyInfoResponse
}
var file_services_companyInfoGetter_companyInfoGetter_proto_depIdxs = []int32{
	0, // 0: CompanyInfoGetter.GetCompanyInfo:input_type -> GetCompanyInfoRequest
	1, // 1: CompanyInfoGetter.GetCompanyInfo:output_type -> GetCompanyInfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_companyInfoGetter_companyInfoGetter_proto_init() }
func file_services_companyInfoGetter_companyInfoGetter_proto_init() {
	if File_services_companyInfoGetter_companyInfoGetter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_companyInfoGetter_companyInfoGetter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCompanyInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_companyInfoGetter_companyInfoGetter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCompanyInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_companyInfoGetter_companyInfoGetter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_companyInfoGetter_companyInfoGetter_proto_goTypes,
		DependencyIndexes: file_services_companyInfoGetter_companyInfoGetter_proto_depIdxs,
		MessageInfos:      file_services_companyInfoGetter_companyInfoGetter_proto_msgTypes,
	}.Build()
	File_services_companyInfoGetter_companyInfoGetter_proto = out.File
	file_services_companyInfoGetter_companyInfoGetter_proto_rawDesc = nil
	file_services_companyInfoGetter_companyInfoGetter_proto_goTypes = nil
	file_services_companyInfoGetter_companyInfoGetter_proto_depIdxs = nil
}
